const fs=require('fs');let s=fs.readFileSync('src/main.ts','utf8');s=s.replace('notified=false;', 'steerVelocity=0;parkFrom=0;parkSpeed=0;freshKey=false;returnFade=0;notified=false;');s=s.replace("this.notified=false;this.age=0;", "this.notified=false;this.steerVelocity=0;this.returnFade=1.2;this.age=0;");
s=s.replace("this.draw();}\n rect", "this.input.keyboard!.on('keydown',()=>{if(this.phase==='course'&&this.age>.3)this.freshKey=true;});this.draw();}\n rect");
s=s.replace("this.phase='course';this.age=0;}} else if(this.phase==='course'){if(this.age>4.5)this.next();}", "this.phase='blackBefore';this.age=0;}} else if(this.phase==='blackBefore'){if(this.age>.8){this.phase='course';this.age=0;this.freshKey=false;}} else if(this.phase==='course'){if(this.freshKey){this.phase='blackAfter';this.age=0;this.freshKey=false;}} else if(this.phase==='blackAfter'){if(this.age>.8){this.phase='later';this.age=0;}} else if(this.phase==='later'){if(this.age>2.2)this.next();}");
s=s.replace("else if(this.phase==='arrival'){if(this.age>1)this.school();}", "else if(this.phase==='arrival'){const p=Math.min(1,this.age/2.8),smooth=p*p*(3-2*p);this.car=this.parkFrom+(1.23-this.parkFrom)*smooth;this.speed=this.parkSpeed*(1-p)*(1-p);this.travel+=this.visualSpeed()*dt;if(this.age>3.3){this.phase='arrivalFade';this.age=0;}}else if(this.phase==='arrivalFade'){if(this.age>1.1)this.school();}");
let a=s.indexOf(' const steer='),b=s.indexOf('if(Math.abs(this.car)>1)',a);s=s.slice(0,a)+` const steer=(this.keys.RIGHT.isDown?1:0)-(this.keys.LEFT.isDown?1:0);const target=steer*(.12+Math.min(1,this.speed/TUNING.maxSpeed)*1.8);this.steerVelocity+=(target-this.steerVelocity)*(1-Math.exp(-dt/(steer?.24:.18)));this.car=Phaser.Math.Clamp(this.car+this.steerVelocity*dt,-1.15,1.15);`+s.slice(b);
s=s.replace('this.travel+=this.speed*dt;', 'this.returnFade=Math.max(0,this.returnFade-dt);this.travel+=this.visualSpeed()*dt;');s=s.replace('o.z-this.travel+this.speed*dt','o.z-this.travel+this.visualSpeed()*dt');s=s.replace("this.phase='arrival';this.age=0;", "this.phase='arrival';this.parkFrom=this.car;this.parkSpeed=this.speed;this.age=0;");
s=s.replace(' hurt(){', ' visualSpeed(){return this.speed*(.35+1.65*(this.speed/TUNING.maxSpeed)**1.4);}\n hurt(){');
s=s.replace("['road','free','receive','arrival']", "['road','free','receive','arrival','arrivalFade']");s=s.replace("['school','opening','course','fail'].includes(this.phase))this.drawSchool();else{", "['school','opening','fail'].includes(this.phase))this.drawSchool();else if(['blackBefore','course','blackAfter','later'].includes(this.phase)){this.rect(5,5,310,172,0x000000);}else{");
s=s.replace("if(this.phase==='arrival')this.banner('ETABLISSEMENT ATTEINT');",'');
s=s.replace("this.g.fillStyle(0x000000,Math.min(1,this.age/1.8));this.g.fillRect(5,5,310,172);", "this.fadeViewport(Math.min(1,this.age/1.8));");s=s.replace("this.txt(77,117,'UNE HEURE PLUS TARD',8);", "");s=s.replace("if(this.phase==='fail'){this.banner", "if(this.phase==='later')this.txt(47,88,'Une heure plus tard...',14);if(this.phase==='arrivalFade')this.fadeViewport(Math.min(1,this.age/1.1));if(this.phase==='free'&&this.returnFade>0)this.fadeViewport(this.returnFade/1.2);if(this.phase==='fail'){this.banner");
s=s.replace(' banner(s:string)', " fadeViewport(alpha:number){for(const t of this.labels)if(t.y<179)t.setAlpha(1-alpha);this.g.fillStyle(0x000000,alpha);this.g.fillRect(5,5,310,172);}\n banner(s:string)");
s=s.replace(' const x=project(0,this.car).x;', ` if(['arrival','arrivalFade'].includes(this.phase)){this.rect(214,48,97,83,0x8a8975);this.rect(209,43,103,8,0x4e544c);for(let i=0;i<4;i++){this.rect(222+i*21, sixty(),13,18,0x293e43);}this.rect(257,96,22,35,0x303732);this.rect(212,132,101,42,0x888778);this.txt(218,84,'COLLEGE',10,'#222c29');}
 const x=project(0,this.car).x;`.replace('sixty()','60'));
fs.writeFileSync('src/main.ts',s);
