const fs=require('fs');let w=fs.readFileSync('src/world.ts','utf8');w=w.replace('  stun: number;', '  stun: number; parent?:boolean; chargeDir?:number; chargeTime?:number;');w=w.replace('  "ESCALIER DE SERVICE",','  "ESCALIER DE SERVICE", "PASSAGE TECHNIQUE / DANGER",');w=w.replace('  2: [],','  2: [{from:205,to:295,key:"UP",label:"HAUT : RACCOURCI / SOL FRAGILE",target:8,spawn:25}],');w=w.replace('  3: [','  8: [{from:10,to:65,key:"DOWN",label:"BAS : RETOUR ESCALIER",target:2,spawn:220}],\n  3: [');w=w.replace('            hp: 2,','            hp: room===1?3:2,parent:room===1,chargeDir:0,chargeTime:0,');fs.writeFileSync('src/world.ts',w);
let s=fs.readFileSync('src/main.ts','utf8');s=s.replace('  audio = new AudioKit();',`  vehicle=100;crashPush=0;hitStop=0;brokenRoad=false;boardMessage='';messageTime=0;kilometers=0;collisions=0;punches=0;shortcuts=0;
  particles:{x:number,y:number,vx:number,vy:number,life:number,color:number}[]=[];
  audio = new AudioKit();`);
s=s.replace('    this.trafficHit = 0;', '    this.trafficHit = 0;this.crashPush=0;this.particles=[];this.brokenRoad=false;if(this.vehicle<=0)this.vehicle=65;');s=s.replace('    this.phase = ok ? "opening" : "fail";', '    this.brokenRoad=["free","receive","road"].includes(this.phase);\n    this.phase = ok ? "opening" : "fail";');s=s.replace('        this.results = [];','        this.results = [];this.vehicle=100;this.kilometers=0;this.collisions=0;this.punches=0;this.shortcuts=0;');
s=s.replace('    this.age += dt;',`    this.messageTime=Math.max(0,this.messageTime-dt);this.particles=this.particles.filter(p=>p.life>0);for(const p of this.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=100*dt;}if(this.hitStop>0){this.hitStop=Math.max(0,this.hitStop-dt);this.draw();return;}
    this.age += dt;`);s=s.replace('    } else if (this.phase === "arrival") {','    } else if(this.phase==="tow"){if(this.age>3){this.vehicle=65;this.begin();}}else if (this.phase === "arrival") {');
s=s.replace('this.car + this.steerVelocity * dt,','this.car + (this.steerVelocity+this.crashPush) * dt,');s=s.replace('      this.trafficHit = Math.max','      this.crashPush*=Math.exp(-dt*8);this.kilometers+=this.speed/3.6*dt/1000;\n      this.trafficHit = Math.max');s=s.replace('          this.speed *= 0.55;\n          this.trafficHit = 1.2;\n          this.cameras.main.shake(80, 0.003);','          this.crash(o.x,o.type);');s=s.replace('      if (cruising && this.age > TUNING.cruiseSeconds)','      if(this.vehicle<=0){if(this.notified)this.finish(false);else{this.phase="tow";this.age=0;}this.draw();return;}\n      if (cruising && this.age > TUNING.cruiseSeconds)');
s=s.replace('          this.impact = 0.15;','          this.hitStop=.055;this.punches++;this.burst(e.x,132,0xeee2b9);\n          this.impact = 0.15;');s=s.replace('        if (e.stun > 0) continue;','        if (e.stun > 0) continue;\n        if(e.parent){this.updateParent(e,dt);continue;}');s=s.replace('      if (this.enemies.every','      if(this.room===8&&this.py===159){for(const [left,right] of [[95,128],[190,223]])if(this.px>left&&this.px<right){this.hurt();this.px=left-10;}}\n      if (this.enemies.every');s=s.replace('          else this.enterRoom(action.target, action.spawn);','          else {if(action.target===8){this.shortcuts++;this.boardMessage="VOTRE AUTONOMIE EST APPRECIEE";this.messageTime=4;}this.enterRoom(action.target, action.spawn);}');s=s.replace('else if (this.room === 7 && this.px < 12) this.enterRoom(6, 280);','else if (this.room === 7 && this.px < 12) this.enterRoom(6, 280);else if(this.room===8&&this.px>298)this.enterRoom(3,100);');
const pos=s.indexOf('  visualSpeed()');s=s.slice(0,pos)+`  burst(x:number,y:number,color:number){for(let i=0;i<8;i++)this.particles.push({x,y,vx:(i-3.5)*18,vy:-35-(i%3)*18,life:.7+i*.035,color});}
 crash(lane:number,type:number){if(this.trafficHit>0||this.vehicle<=0)return;this.collisions++;this.vehicle=Math.max(0,this.vehicle-(type===1?30:22));this.speed*=.48;this.trafficHit=1.4;this.crashPush=(this.car>=lane?1:-1)*.7;this.burst(160+this.car*105,148,0xdba15d);this.audio.tone(72,.2,.065,24);this.cameras.main.shake(170,.008);this.boardMessage='VEHICULE PERSONNEL : A VOTRE CHARGE';this.messageTime=3;}
 updateParent(e:Enemy,dt:number){if(e.recovery>0){e.recovery-=dt;return;}if((e.chargeTime??0)>0){e.chargeTime!-=dt;e.x+=(e.chargeDir??1)*190*dt;if(Math.abs(e.x-this.px)<22&&this.py>130)this.hurt();if(e.x<29||e.x>275){e.x=Phaser.Math.Clamp(e.x,29,275);e.hp--;e.chargeTime=0;e.stun=1.1;e.recovery=.5;this.burst(e.x,136,0xbab099);this.audio.tone(90,.16,.05,28);this.boardMessage='INCIDENT MOBILIER ENREGISTRE';this.messageTime=3;}else if(e.chargeTime!<=0)e.recovery=.8;return;}if(e.wind>0){e.wind-=dt;if(e.wind<=0){e.chargeTime=1.25;this.audio.tone(200,.12,.02,70);}return;}e.cool-=dt;if(Math.abs(e.x-this.px)<185&&e.cool<=0){e.wind=.7;e.chargeDir=Math.sign(this.px-e.x)||-1;e.cool=1.3;}else if(Math.abs(e.x-this.px)>60)e.x+=Math.sign(this.px-e.x)*18*dt;}
 vehicleDamage(x:number,y:number,side=false){if(this.vehicle>70)return;this.rect(x-12,y,side?24:18,3,0x333b39);this.rect(x+8,y-8,4,6,0x292c2a);if(this.vehicle<=40){this.rect(x-9,y-17+Math.sin(this.age*18)*2,21,3,0x7e5b3c);for(let i=0;i<5;i++){const p=(this.age*.8+i/5)%1;this.rect(x-5+p*12,y-20-p*30,4+p*6,4+p*5,0x92998c);}}}
 `+s.slice(pos);
s=s.replace('    if (["road", "free", "receive"].includes(this.phase)) this.drawRoad();','    if (["road", "free", "receive","tow"].includes(this.phase)||(this.phase==="fail"&&this.brokenRoad)) this.drawRoad();');s=s.replace('    this.rect(x + 6, 158, 7, 3, 0xe66053);','    this.rect(x + 6, 158, 7, 3, 0xe66053);this.vehicleDamage(x,165);');s=s.replace('    if (t > 1.9 && t < 2.8)','    this.vehicleDamage(carX,146,true);\n    if (t > 1.9 && t < 2.8)');
s=s.replace('      `SERVICES ${this.won}/2  /  VEUILLEZ RESPECTER LE CADRE`,','      this.messageTime>0?this.boardMessage:`SERVICES ${this.won}/2  /  VEUILLEZ RESPECTER LE CADRE`,');s=s.replace('    if (this.phase === "receive") {\n      this.rect(41,','    if(["free","receive","road","arrival","arrivalFade","tow"].includes(this.phase)){this.rect(10,158,80,16,0x14201d);this.txt(14,160,`ETAT AUTO ${this.vehicle}%`,8,this.vehicle<=40?"#f58f76":"#e1d6ae");}\n    if (this.phase === "receive") {\n      this.rect(41,');s=s.replace('      this.banner("CARENCE CONSTATEE");','      this.banner(this.vehicle<=0?"PANNE / MISSION PERDUE":"CARENCE CONSTATEE");if(this.vehicle<=0)this.txt(40,116,"DEPANNAGE PUIS AFFECTATION SUIVANTE",8);');s=s.replace('    if (this.paused) this.banner("PAUSE");','    if(this.phase==="tow"){this.banner("DEPANNAGE EN COURS");this.txt(45,120,"VEHICULE PERSONNEL : VOS FRAIS",8);}\n    for(const p of this.particles)if(p.x>8&&p.x<308&&p.y>8&&p.y<173)this.rect(p.x,p.y,3,2,p.color);\n    if (this.paused) this.banner("PAUSE");');
s=s.replace('    if (this.room === 2) {','    if(this.room===1){for(const x of [15,278]){this.rect(x,142,24,17,0x77654e);this.rect(x+4,135,16,7,0x9b8b68);}}\n    if (this.room === 2) {');s=s.replace('      this.txt(35, 95, "< RETOUR AU HALL", 9);','      this.txt(25,95,"< DETOUR SUR / RACCOURCI RISQUE >",8);');s=s.replace('    for (const e of this.enemies)\n      if (e.hp > 0)','    if(this.room===8){this.txt(37,63,"SOL FRAGILE / SAUTEZ LES TROUS",9,"#edc878");for(const x of [95,190])this.rect(x,159,33,16,0x090d13);this.txt(202,94,"AILE C >",9);}\n    if(this.room===3){this.rect(128,108,13,14,0x2b423b);this.rect(130,118,3,4,0xbfa783);this.rect(136,118,3,4,0xbfa783);this.txt(120,76,"COURS EN COURS",7);}\n    for (const e of this.enemies)\n      if (e.hp > 0)');s=s.replace('        if (e.boss && e.recovery > 0.8)','        if(e.parent){this.rect(e.x-7,127,14,4,0x715546);if(e.wind>0)this.txt(64,91,"VOUS ETES ENCORE EN RETARD !",8,"#e8bb87");if(e.stun>0)this.txt(e.x-10,115,"***",10,"#f3d686");if((e.chargeTime??0)>0)this.rect(e.x-18,151,12,2,0xcbb790);}\n        if (e.boss && e.recovery > 0.8)');s=s.replace('        if (preview === "inspecteur")','        if(preview==="parent")this.enterRoom(1,90);if(preview==="raccourci")this.enterRoom(8,25);\n        if (preview === "inspecteur")');
fs.writeFileSync('src/main.ts',s);
